base_model: "resnet50"
meta_lr_inner: 1e-3
meta_lr_outer: 1e-4
num_inner_steps: 3
meta_batch_size: 2
meta_epochs: 5

tasks: ["illumination"] # meta-train *on illumination*
pretrained_path: "results/checkpoints/resnet50_finetuned_view.pth"

save_path: "results/checkpoints/resnet50_meta_from_view_to_illum.pth"